/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/layouts/AppBreadcrumb.vue')['default']
    AppConfig: typeof import('./src/components/layouts/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/layouts/AppFooter.vue')['default']
    AppLayout: typeof import('./src/components/layouts/AppLayout.vue')['default']
    AppMenu: typeof import('./src/components/layouts/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/components/layouts/AppMenuItem.vue')['default']
    AppMenuParent: typeof import('./src/components/layouts/AppMenuParent.vue')['default']
    AppMenuStaff: typeof import('./src/components/layouts/AppMenuStaff.vue')['default']
    AppMenuStudent: typeof import('./src/components/layouts/AppMenuStudent.vue')['default']
    AppMenuTeacher: typeof import('./src/components/layouts/AppMenuTeacher.vue')['default']
    AppRightMenu: typeof import('./src/components/layouts/AppRightMenu.vue')['default']
    AppSidebar: typeof import('./src/components/layouts/AppSidebar.vue')['default']
    AppSidebarParent: typeof import('./src/components/layouts/AppSidebarParent.vue')['default']
    AppSidebarStaff: typeof import('./src/components/layouts/AppSidebarStaff.vue')['default']
    AppSidebarStudent: typeof import('./src/components/layouts/AppSidebarStudent.vue')['default']
    AppSidebarTeacher: typeof import('./src/components/layouts/AppSidebarTeacher.vue')['default']
    AppTopbar: typeof import('./src/components/layouts/AppTopbar.vue')['default']
    AppTopBarBlank: typeof import('./src/components/layouts/AppTopBarBlank.vue')['default']
    AppTopbarDefault: typeof import('./src/components/layouts/AppTopbarDefault.vue')['default']
    AppTopbarParent: typeof import('./src/components/layouts/AppTopbarParent.vue')['default']
    AppTopbarStaff: typeof import('./src/components/layouts/AppTopbarStaff.vue')['default']
    AppTopbarStudent: typeof import('./src/components/layouts/AppTopbarStudent.vue')['default']
    AppTopbarTeacher: typeof import('./src/components/layouts/AppTopbarTeacher.vue')['default']
    Button: typeof import('primevue/button')['default']
    CardBranch: typeof import('./src/components/card-branch.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ComApp: typeof import('./src/components/bases/com-app.vue')['default']
    ComCard: typeof import('./src/components/com-card.vue')['default']
    ComJson: typeof import('./src/components/bases/com-json.vue')['default']
    ComTodo: typeof import('./src/components/com-todo.vue')['default']
    ComTodoList: typeof import('./src/components/com-todo-list.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogAddDeveloper: typeof import('./src/components/dialogs/dialog-add-developer.vue')['default']
    DialogModule: typeof import('./src/components/dialogs/dialog-module.vue')['default']
    DialogPermission: typeof import('./src/components/dialogs/dialog-permission.vue')['default']
    DialogSearch: typeof import('./src/components/dialogs/dialog-search.vue')['default']
    Image: typeof import('primevue/image')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
  }
}
